apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: foo
spec:
  replicas: 3
  selector:
    matchLabels:
      red: blue
  template:
    metadata:
      name: foo
      labels:
        red: blue
    spec:
      containers:
      - image: nginx
        name: nginx
