apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: wordpress.192.168.99.100.nip.io
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
