apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: oreilly
spec:
  containers:
  - image: redis:3.2
    imagePullPolicy: IfNotPresent
    name: redis
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
  restartPolicy: Always
