apiVersion: v1
kind: Pod
metadata:
  name: multi
  namespace: oreilly
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  - image: redis
    name: redis
  restartPolicy: Always
