apiVersion: v1
kind: Service
metadata:
  name: myexternaldb
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: myexternaldb
subsets:
  - addresses:
    ips:
    - 1.2.3.4
    ports:
    - port: 3306

