apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /bitnami
      name: foobar
  volumes:
  - name: foobar
    persistentVolumeClaim:
      claimName: myclaim
